### ISSUE TITLE
1.4.0: `Metorik_Custom::scripts_styles()` cart performance problem

### ISSUE THREAD

**Issue by lkraav** [metorikhq/metorik-helper#99]
Background: https://github.com/woocommerce/woocommerce/issues/20937#issuecomment-414065757

Our site frontend page build speed has reached hurt stage due to WooCommerce cart system loading on every frontend request.

Many things hook into it, and add multiple 100s ms of PHP processing time for a thing nobody potentially sees (obviously depends on the site).

Some profiler callgraph cutout proof below (I've already monkey-patched Metorik cart out here, but core is still there):

![image](https://user-images.githubusercontent.com/147228/83131876-38dc3080-a0e9-11ea-8a42-67406ec32573.png)

I was able to unhook core WooCommerce cart auto-load system, but it turned out Metorik still triggers cart load at https://github.com/metorikhq/metorik-helper/blob/1.4.0/inc/custom.php#L78

Can we add a filter to conditionally opt into this particular field? (for example, I'd only enable it on `is_checkout()`)

Also, what are the implications of such in Metorik reporting app UI?

I think the remaining data collection is not as resource-intensives, so I'm currently not thinking about dequeuing all fields, even though I'm not really sure whether our analysts really use it in Metorik in any way.

**Comment by bryceadams** [comment]
Nice research into this here @lkraav! Much appreciated.

So... good question. We do require it on your store if you're using cart tracking, as we need the count that way in order to determine when it asks for customer emails etc.

You can probably get away without it though if you **are not** using the add to cart email popup. In your case, are you using that? If not, then I should probably look at automatically **not calculating it** for stores that don't need it, considering the performance impact it's having for you.

Your other suggestion to filter it so you can decide when it gets loaded could help too.

I'd say for now:

1. Let me know re: the above as curious if you're using and then I may end up tweaking it in the next version to only load the cart when needed. Otherwise I may just add a filter so you can over-ride it in certain cases and stop the cart loading.

2. Perhaps try remove that param from the plugin manually now and see if it solves the performance issues you were looking into? Would be curious to know if so.

LMK and we'll chat further - cheers! :)

**Comment by lkraav** [comment]
> You can probably get away without it though if you are not using the add to cart email popup. In your case, are you using that? If not, then I should probably look at automatically not calculating it for stores that don't need it, considering the performance impact it's having for you.

I didn't even know what this Metorik feature is.

Checked https://app.metorik.com/cart-settings now and it looks like we have cart tracking enabled, but popup has been disabled. We're currently using AutomateWoo already for cart recovery.. it's probably safe to exclude Metorik for now.

> Perhaps try remove that param from the plugin manually now and see if it solves the performance issues you were looking into? Would be curious to know if so.

Yep, monkey-patched it already (items always 0), and it successfully eliminates core cart processing callgraph branch. (Only in combination with other relevant work linked earlier.)

**Comment by bryceadams** [comment]
Awesome, good to know. I'll make some improvements and also add a filter in
the next release. Cheers!

**Comment by lkraav** [comment]
Looks like didn't make it to 1.4.1, so still monkey-patching live. Any love available here for 1.4.2?

**Comment by bryceadams** [comment]
Apologies Leho! Had to get that update out quickly and didn't have time to test and implement a solution here for this. I've made a note so I should get this into the next update when we do one. Cheers!

**Comment by bryceadams** [comment]
This is fixed in the upcoming 1.5.0 release (probably sometime this month or in January).

This code can be used to disable the cart items code:

```
add_filter('metorik_cart_items', '__return_false');
```
